version: '3.8'

services:
  app:
    build: .
    container_name: google-maps-scraper
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    volumes:
      # Optional: Mount logs directory if you want persistent logs
      - ./logs:/app/logs
    # Chromium runs with --no-sandbox flag, so no special capabilities needed
    # If you experience issues, you can uncomment the following (less secure):
    # security_opt:
    #   - seccomp:unconfined
