version: '3.8'

services:
  app:
    build: .
    container_name: google-maps-scraper
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    volumes:
      # Optional: Mount logs directory if you want persistent logs
      - ./logs:/app/logs
    # Add security options for running Chromium
    cap_add:
      - SYS_ADMIN
    # Alternative to SYS_ADMIN (more secure but may not work in all environments)
    # security_opt:
    #   - seccomp:unconfined
